FROM node:24-alpine

WORKDIR /app

COPY docker-entrypoint-dev.sh /usr/local/bin/docker-entrypoint-dev.sh
RUN chmod +x /usr/local/bin/docker-entrypoint-dev.sh

ENTRYPOINT ["/usr/local/bin/docker-entrypoint-dev.sh"]
CMD ["node", "index.mjs"]
